# Generated by Django 4.1.5 on 2023-01-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_members_created_at_alter_members_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='birthdate',
        ),
    ]
