# Generated by Django 4.1.5 on 2023-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
